%%%%%% DOCUMENT SETUP %%%%%%

fileID = fopen('scramble2_report.html', 'w');
doc_title = sprintf('Scrambling Experiment 2');
h1 = sprintf('Scrambling Experiment 2');
doc_subtitle = sprintf(['' ...
    'Variant: Only move around freqs from 1:160 and 801:960. (Same range as scramble1, but with different permutation.)' ...
    '']);
img_res = 80; % MATLAB's default is 150

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
tic
% based on source_h (from /botol/) but with pre-computed FFTs

load('lut.mat');

[y, f] = audioread("botol.wav");    % amplitude vs frequency
n = 0.02 * f;                       % panjang array audio selama 20 ms
fc = 7000/(f/2);

f_audio_init = figure('visible', 'off');
f_audio_init.Position(3:4) = [450 400];
plot(y);
title("Initial input audio in time domain");
exportgraphics(f_audio_init, 'f_audio_init.png', 'Resolution', img_res);

z = zeros(ceil(length(y)/n), n);
counter = 1;
for m = n:n:length(y)
    z(counter, :) = y(n*(counter-1)+1:m, 1);
    counter = counter + 1;
end

Z = readmatrix("botol_fft_z.csv");
Zi = readmatrix("botol_fft_zi.csv");

f_Z_100 = figure('visible', 'off');
f_Z.Position(3:4) = [450 250];
plot((abs(real(Z(100,:)))));
title("Z before scrambling (real absolute parts) (100, :)");
exportgraphics(f_Z_100, 'f_Z_100.png', 'Resolution', img_res);

f_Zi_100 = figure('visible', 'off');
f_Zi.Position(3:4) = [450 250];
plot((abs(real(Zi(100,:)))));
title("Zi before scrambling (real absolute parts) (100, :)");
exportgraphics(f_Zi_100, 'f_Zi_100.png', 'Resolution', img_res);

temp1 = [];
temp2 = [];
R = zeros(ceil(length(y)/n), n);
Ri = zeros(ceil(length(y)/n), n);

% Notes
desc_scramble = sprintf(['' ...
    'Scrambling configuration notes: <br/>' ...
    '<table class="bordered-table">' ...
        '<tr>' ...
            '<th>LF config</th>' ...
            '<th>HF config</th>' ...
            '<th>Comments</th>' ...
        '</tr>' ...
        '<tr>' ...
            '<td><code>temp1(1:160) = [A1, B1, C1, D1, E1, F1, G1, H1];</code></td>' ...
            '<td><code>temp1(801:960) = [I1, J1, K1, L1, M1, N1, O1, P1];</code></td>' ...
            '<td>No scrambling. (For comparison.)</td>' ...
        '</tr>' ...
        '<tr>' ...
            '<td><code>temp1(1:160) = [F1, E1, H1, G1, B1, A1, D1, C1];</code></td>' ...
            '<td><code>temp1(801:960) = [N1, M1, P1, O1, J1, I1, L1, K1];</code></td>' ...
            '<td>Scrambled audio inaudible and reconstruction is pretty good.</td>' ...
        '</tr>' ...
        '<tr>' ...
            '<td><code>temp1(1:160) = [D1, C1, B1, A1, H1, G1, F1, E1];</code></td>' ...
            '<td><code>temp1(801:960) = [N1, M1, P1, O1, J1, I1, L1, K1];</code></td>' ...
            '<td>Scrambled audio high-pitched and distorted but a few words still audible. Noisy reconstructed audio.</td>' ...
        '</tr>' ...
        '<tr>' ...
            '<td><code>temp1(1:160) = [B1, A1, G1, H1, D1, C1, F1, E1]; </code></td>' ...
            '<td><code>temp1(801:960) = [N1, M1, P1, O1, J1, I1, L1, K1];</code></td>' ...
            '<td>Scrambled audio high-pitched and distorted but a few words still audible. Noisy reconstructed audio.</td>' ...
        '</tr>' ...
        '<tr>' ...
            '<td><code>temp1(1:160) = [C1, D1, G1, H1, B1, A1, F1, E1]; </code></td>' ...
            '<td><code>temp1(801:960) = [N1, M1, P1, O1, J1, I1, L1, K1];</code></td>' ...
            '<td>Scrambled audio inaudible. Reconstructed audio is almost inaudible and very terrible.</td>' ...
        '</tr>' ...
        '<tr>' ...
            '<td><code>temp1(1:160) = [A1, H1, C1, F1, E1, B1, G1, D1]; </code></td>' ...
            '<td><code>temp1(801:960) = [N1, M1, P1, O1, J1, I1, L1, K1];</code></td>' ...
            '<td>The reconstructed audio is terrible (but audible). And then somehow the scrambled audio is more audible than the reconstructed audio.</td>' ...
        '</tr>' ...
        '<tr>' ...
            '<td><code>temp1(1:160) = [H1, A1, B1, C1, D1, E1, F1, G1]; </code></td>' ...
            '<td><code>temp1(801:960) = [N1, M1, P1, O1, J1, I1, L1, K1];</code></td>' ...
            '<td>Ineffective scrambling (only became more high pitched mostly) and terrible reconstruction (audible but uncomfortable).</td>' ...
        '</tr>' ...
        '<tr>' ...
            '<td><code>temp1(1:160) = [G1, H1, A1, B1, C1, D1, E1, F1]; </code></td>' ...
            '<td><code>temp1(801:960) = [N1, M1, P1, O1, J1, I1, L1, K1];</code></td>' ...
            '<td>Slightly more scrambled but still ineffective. Reconstruction is still awful..</td>' ...
        '</tr>' ...
        '<tr>' ...
            '<td><code>temp1(1:160) = [F1, G1, H1, A1, B1, C1, D1, E1]; </code></td>' ...
            '<td><code>temp1(801:960) = [N1, M1, P1, O1, J1, I1, L1, K1];</code></td>' ...
            '<td>Mostly scrambled but still kinda audible. Reconstruction is better, with some high-pitched noise.</td>' ...
        '</tr>' ...
        '<tr>' ...
            '<td><code>temp1(1:160) = [E1, F1, G1, H1, A1, B1, C1, D1]; </code></td>' ...
            '<td><code>temp1(801:960) = [N1, M1, P1, O1, J1, I1, L1, K1];</code></td>' ...
            '<td>Inaudible high-pitched scramble. Easy to understand but noisy reconstruction. Note: somehow could be reconstructed using [F1, G1, H1, A1, B1, C1, D1, E1] key.</td>' ...
        '</tr>' ...
        '<tr>' ...
            '<td><code>temp1(1:160) = [E1, F1, G1, H1, C1, D1, A1, B1]; </code></td>' ...
            '<td><code>temp1(801:960) = [N1, M1, P1, O1, J1, I1, L1, K1];</code></td>' ...
            '<td>Mostly inaudible scrambling but some words are audible if you concentrate. Audible but very noisy reconstruction.</td>' ...
        '</tr>' ...
        '<tr>' ...
            '<td><code>temp1(1:160) = [G1, H1, E1, F1, C1, D1, A1, B1]; </code></td>' ...
            '<td><code>temp1(801:960) = [N1, M1, P1, O1, J1, I1, L1, K1];</code></td>' ...
            '<td>Inaudible scrambling (tone/enunciation still leaks a bit). Okay but not good reconstruction.</td>' ...
        '</tr>' ...
        '<tr>' ...
            '<td><code>temp1(1:160) = [G1, H1, E1, F1, D1, C1, A1, B1]; </code></td>' ...
            '<td><code>temp1(801:960) = [N1, M1, P1, O1, J1, I1, L1, K1];</code></td>' ...
            '<td>Mostly scrambled but more audible than [G1, H1, E1, F1, C1, D1, A1, B1]. Better reconstruction with some noise.</td>' ...
        '</tr>' ...
        '<tr>' ...
            '<td><code>temp1(1:160) = [H1, G1, E1, F1, D1, C1, A1, B1]; </code></td>' ...
            '<td><code>temp1(801:960) = [N1, M1, P1, O1, J1, I1, L1, K1];</code></td>' ...
            '<td>Mostly scrambled but more audible than [G1, H1, E1, F1, C1, D1, A1, B1]. Audible but very noisy reconstruction.</td>' ...
        '</tr>' ...
        '<tr>' ...
            '<td><code>temp1(1:160) = [H1, G1, E1, F1, D1, C1, B1, A1]; </code></td>' ...
            '<td><code>temp1(801:960) = [N1, M1, P1, O1, J1, I1, L1, K1];</code></td>' ...
            '<td>Mostly scrambled but more audible than [G1, H1, E1, F1, C1, D1, A1, B1]. Worse and noisy reconstruction.</td>' ...
        '</tr>' ...
        '<tr>' ...
            '<td><code>temp1(1:160) = [H1, G1, E1, F1, D1, C1, B1, A1]; </code></td>' ...
            '<td><code>temp1(801:960) = [N1, M1, P1, O1, J1, I1, L1, K1];</code></td>' ...
            '<td>Slightly better scrambled. Mostly good reconstruction.</td>' ...
        '</tr>' ...
        '<tr>' ...
            '<td><code>temp1(1:160) = [H1, G1, F1, E1, D1, C1, B1, A1]; </code></td>' ...
            '<td><code>temp1(801:960) = [N1, M1, P1, O1, J1, I1, L1, K1];</code></td>' ...
            '<td>Same same. Slightly worse reconstruction.</td>' ...
        '</tr>' ...
        '<tr>' ...
            '<td><code>temp1(1:160) = [H1, G1, F1, E1, D1, C1, B1, A1]; </code></td>' ...
            '<td><code>temp1(801:960) = [I1, J1, K1, L1, M1, N1, O1, P1];</code></td>' ...
            '<td>NOT scrambled at all.</td>' ...
        '</tr>' ...
        '<tr>' ...
            '<td><code>temp1(1:160) = [H1, G1, F1, E1, D1, C1, B1, A1]; </code></td>' ...
            '<td><code>temp1(801:960) = [M1, N1, O1, P1, I1, J1, K1, L1];</code></td>' ...
            '<td>Still slightly audible. Very good reconstruction.</td>' ...
        '</tr>' ...
        '<tr>' ...
            '<td><code>temp1(1:160) = [H1, G1, F1, E1, D1, C1, B1, A1]; </code></td>' ...
            '<td><code>temp1(801:960) = [M1, N1, O1, P1, K1, L1, I1, J1];</code></td>' ...
            '<td>Still slightly audible. Very good reconstruction.</td>' ...
        '</tr>' ...
        '<tr>' ...
            '<td><code>temp1(1:160) = [H1, G1, F1, E1, D1, C1, B1, A1]; </code></td>' ...
            '<td><code>temp1(801:960) = [O1, P1, M1, N1, K1, L1, I1, J1];</code></td>' ...
            '<td>Still slightly audible. Good reconstruction (better yet).</td>' ...
        '</tr>' ...
        '<tr>' ...
            '<td><code>temp1(1:160) = [H1, G1, F1, E1, D1, C1, B1, A1]; </code></td>' ...
            '<td><code>temp1(801:960) = [P1, O1, N1, M1, L1, K1, J1, I1];</code></td>' ...
            '<td>Scramble is still slightly audible, but the reconstruction is very good with minimum noise. Notice that the scrambling configurations for (1:160) and (801:960) are "similar".</td>' ...
        '</tr>' ...
        '<tr>' ...
            '<td><code>temp1(1:160) = [H1, G1, F1, E1, B1, A1, D1, C1]; </code></td>' ...
            '<td><code>temp1(801:960) = [P1, O1, N1, M1, J1, I1, L1, K1];</code></td>' ...
            '<td>Scramble is still slightly audible, slightly noisier but still overall good reconstruction. Notice that the scrambling configurations for (1:160) and (801:960) are "similar".</td>' ...
        '</tr>' ...
        '<tr>' ...
            '<td><code>temp1(1:160) = [H1, G1, F1, E1, B1, A1, D1, C1]; </code></td>' ...
            '<td><code>temp1(801:960) = [N1, M1, P1, O1, J1, I1, L1, K1];</code></td>' ...
            '<td>Noisier reconstruction. Scrambling configurations no longer as "similar".</td>' ...
        '</tr>' ...
       '</table>' ...
    '<br/>']);

for m = 1:counter
    temp1 = Z(m, :);
    temp2 = Zi(m, :);

    A1 = temp1(1:20);
    B1 = temp1(21:40);
    C1 = temp1(41:60);
    D1 = temp1(61:80);
    E1 = temp1(81:100);
    F1 = temp1(101:120);
    G1 = temp1(121:140);
    H1 = temp1(141:160);

    A2 = temp2(1:20);
    B2 = temp2(21:40);
    C2 = temp2(41:60);
    D2 = temp2(61:80);
    E2 = temp2(81:100);
    F2 = temp2(101:120);
    G2 = temp2(121:140);
    H2 = temp2(141:160);

    % note: as a reference, source_h is (f, e, h, g, b, a, d, c)
    temp1(1:160) = [H1, G1, F1, E1, B1, A1, D1, C1];
    temp2(1:160) = [H2, G2, F2, E2, B2, A2, D2, C2];

    I1 = temp1(801:820);
    J1 = temp1(821:840);
    K1 = temp1(841:860);
    L1 = temp1(861:880);
    M1 = temp1(881:900);
    N1 = temp1(901:920);
    O1 = temp1(921:940);
    P1 = temp1(941:960);

    I2 = temp2(801:820);
    J2 = temp2(821:840);
    K2 = temp2(841:860);
    L2 = temp2(861:880);
    M2 = temp2(881:900);
    N2 = temp2(901:920);
    O2 = temp2(921:940);
    P2 = temp2(941:960);
    
    % note: as a reference, source_h is (n, m, p, o, j, i, l, k)
    temp1(801:960) = [N1, M1, P1, O1, J1, I1, L1, K1];
    temp2(801:960) = [N2, M2, P2, O2, J2, I2, L2, K2];

    R(m,:) = temp1;
    Ri(m,:) = temp2;

    temp1 = [];
    temp2 = [];
end

f_R_100 = figure('visible', 'off');
f_R.Position(3:4) = [450 250];
plot((abs(real(R(100,:)))));
title("R after scrambling (real absolute parts) (100, :)");
exportgraphics(f_R_100, 'f_R_100.png', 'Resolution', img_res);

f_Ri_100 = figure('visible', 'off');
f_Ri.Position(3:4) = [450 250];
plot((abs(real(Ri(100,:)))));
title("Ri after scrambling (real absolute parts) (100, :)");
exportgraphics(f_Ri_100, 'f_Ri_100.png', 'Resolution', img_res);

for m = 1:counter
    re(m, :) = mat_ifft(R(m,:), Ri(m,:), r, i);
end

c = [];
for m = 1:counter
    c = [c real(re(m,:))];
end

f_audio_out = figure('visible', 'off');
f_audio_out.Position(3:4) = [450 400];
plot(c);
title("Resulting output audio in time domain");
exportgraphics(f_audio_out, 'f_audio_out.png', 'Resolution', img_res);

audiowrite('botol_scrambled.wav', c, f);

%%%%%%%%%%%%%%

[c, f] = audioread("botol_scrambled.wav");

x = zeros(ceil(length(y)/n), n);
counter = 1;
for m = n:n:length(y)
    x(counter, :) = c(n*(counter-1)+1:m, 1);
    counter = counter + 1;
end

X = zeros(counter,960);
Xi = zeros(counter,960);

for m=1:counter
    [X(m,:), Xi(m,:)] = mat_fft(x(m,:), r, i);
end

% Proses inversi scramble dengan benar pada urutan frekuensi yang tepat
% note: if the scramble configuration was e.g. (f, e, h, g, b, a, d, c)
% it will be the same for the descramble

B = zeros(ceil(length(y)/n),n);
b = zeros(ceil(length(y)/n),n);
for m=1:counter
    temp1 = X(m, :);
    temp2 = Xi(m, :);

    A1 = temp1(1:20);
    B1 = temp1(21:40);
    C1 = temp1(41:60);
    D1 = temp1(61:80);
    E1 = temp1(81:100);
    F1 = temp1(101:120);
    G1 = temp1(121:140);
    H1 = temp1(141:160);

    A2 = temp2(1:20);
    B2 = temp2(21:40);
    C2 = temp2(41:60);
    D2 = temp2(61:80);
    E2 = temp2(81:100);
    F2 = temp2(101:120);
    G2 = temp2(121:140);
    H2 = temp2(141:160);

    % Inversi urutan scrambling untuk frekuensi rendah dan tinggi
    temp1(1:160) = [H1, G1, F1, E1, B1, A1, D1, C1];
    temp2(1:160) = [H2, G2, F2, E2, B2, A2, D2, C2];

    I1 = temp1(801:820);
    J1 = temp1(821:840);
    K1 = temp1(841:860);
    L1 = temp1(861:880);
    M1 = temp1(881:900);
    N1 = temp1(901:920);
    O1 = temp1(921:940);
    P1 = temp1(941:960);

    I2 = temp2(801:820);
    J2 = temp2(821:840);
    K2 = temp2(841:860);
    L2 = temp2(861:880);
    M2 = temp2(881:900);
    N2 = temp2(901:920);
    O2 = temp2(921:940);
    P2 = temp2(941:960);
    
    temp1(801:960) = [N1, M1, P1, O1, J1, I1, L1, K1];
    temp2(801:960) = [N2, M2, P2, O2, J2, I2, L2, K2];

    B(m,:) = temp1;
    Bi(m,:) = temp2;
end

for m=1:counter
    b(m,:)=mat_ifft(B(m,:), Bi(m,:), r, i);
end

d = [];
for m = 1:counter
    d = [d real(b(m,:))];
end

f_audio_recon = figure('visible', 'off');
f_audio_recon.Position(3:4) = [450 400];
plot(d);
title("Reconstructed descrambled audio in time domain");
exportgraphics(f_audio_recon, 'f_audio_recon.png', 'Resolution', img_res);

audiowrite('botol_recon.wav', d, f);

%%%%%%%%%%%%%%%%%%

document_start = sprintf([ ... 
    '<!DOCTYPE html>' ...
    '<html>' ...
        '<head>' ...
            '<title>', doc_title, '</title>' ...
            '<style>' ...
                '.bordered-table, .bordered-table tr, .bordered-table tr td, .bordered-table tr th {border: 1px solid gray; border-collapse: collapse;}' ...
            '</style>' ...
        '</head>' ...
        '<body>' ...
        '<center>'
]);

document_heading = sprintf([ ...
    '<h1>', h1, '</h1>' ...
    '<p>', doc_subtitle, '</p>' ...
    '<p> Image resolution for plots: ', num2str(img_res), '</p>' ...
    '<p>Fs = ', num2str(f), ', Fc = ', num2str(fc), '</p>' ...
    '<p>n = ', num2str(length(y)), ', ', num2str(length(c)), ', ', num2str(length(d)), ' for input, scrambled, and reconstructed audio respectively.</p>' ...
    '<br/>'
    ]);

document_end = sprintf([ ...
        '</body>' ...
        '</center>' ...
    '</html>'
    ]);

fprintf(fileID, document_start);
fprintf(fileID, document_heading);

fprintf(fileID, desc_scramble);

fprintf(fileID, [ ...
    '<table class="table-no-border">' ...
        '<tr>' ...
            '<td><img src="f_audio_init.png"/></td>' ...
            '<td><img src="f_audio_out.png"/></td>' ...
            '<td><img src="f_audio_recon.png"/></td>' ...
        '</tr>' ...
        '<tr>' ...
            '<td><audio controls src="botol.wav"></audio></td>' ...
            '<td><audio controls src="botol_scrambled.wav"></audio></td>' ...
            '<td><audio controls src="botol_recon.wav"></audio></td>' ...
        '</tr>' ...
    '</table>' ...
    '<table>' ...
        '<tr>' ...
            '<td><img src="f_Z_100.png"/></td>' ...
            '<td><img src="f_R_100.png"/></td>' ...
        '</tr>' ...
        '<tr>' ...
            '<td><img src="f_Zi_100.png"/></td>' ...
            '<td><img src="f_Ri_100.png"/></td>' ...
        '</tr>' ...
    '</table>' ...
    ]);

%%%%%% END DOCUMENT %%%%%%

fprintf(fileID, document_end);
fclose(fileID);

toc
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%5

function [R, I] = mat_fft(x, r, i)
    temp1 = 0;
    temp2 = 0;

    R = zeros(1, 960);
    I = zeros(1, 960);

    % actual algorithm:
    % for k = 0:959
    %   for n = 0:959
    %       idx = mod(k*n, 960) + 1
    %       temp1 = temp1 + (x(n+1) * r(idx));
    %       temp2 = temp2 + (x(n+1) * -i(idx));
    %
    %   end "for n"
    %
    %   R(k+1) = fi(temp1);
    %   I(k+1) = fi(temp2);
    %   temp1 = 0;
    %   temp2 = 0;
    %
    % end "for k" 

    for k = 0:959
        idx = -k + 1; % so that at n = 0, "idx = idx + k" = 1
        for n = 0:959 
            idx = idx + k;
            if (idx > 960)
                idx = idx - 960;
            end
            temp1 = temp1 + (x(n+1) * r(idx));
            temp2 = temp2 + (x(n+1) * -i(idx));
        end

        R(k+1) = fi(temp1);
        I(k+1) = fi(temp2);

        temp1 = 0;
        temp2 = 0;
    end
end

function x = mat_ifft(R, I, r, i)
    x = zeros(1, 960);
    temp = 0;
    for n = 0:959
        for k = 0:959
            idx = mod(k*n, 960) + 1;
            temp = temp + ((R(k+1))*r(idx) - I(k+1)*i(idx));
        end
        x(n+1) = temp;
        temp = 0;
    end
    x = (x/960);
end
